version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14  # O la imagen de tu preferencia
    steps:
      - checkout

      - run:
          name: Instalar SonarScanner
          command: |
            curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
            unzip sonar-scanner.zip
            sudo mv sonar-scanner-4.6.2.2472-linux /usr/local/sonar-scanner  # Instalar en /usr/local/sonar-scanner
            echo 'export PATH=$PATH:/usr/local/sonar-scanner/bin' >> $BASH_ENV  # Agregar al PATH de la sesión de CircleCI
            source $BASH_ENV  # Aplicar el cambio a la sesión

      - run:
          name: Ejecutar SonarScanner
          command: |
            sonar-scanner \
              -Dsonar.projectKey=mi_proyecto \
              -Dsonar.host.url=http://localhost:9000 \
              -Dsonar.login=$SONAR_TOKEN

workflows:
  version: 2
  test_and_scan:
    jobs:
      - build
